### ISSUE TITLE
【依頼】ChatSpace挙動確認」

### ISSUE THREAD

**Issue by yukitaka0915-se** [yukitaka0915-se/chat-space#31]
# IPアドレス
13.114.17.218

**Comment by kohei-isoda** [comment]
加藤さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**◯ グループ作成画面が崩れてしまっている（以下画像参照）**
[![Screenshot from Gyazo](https://gyazo.com/6b3a350ba26d5948615fe34e353af5f1/raw)](https://gyazo.com/6b3a350ba26d5948615fe34e353af5f1)

`※ 見本は以下です。`
[![Screenshot from Gyazo](https://gyazo.com/a9d9edade3e12eb4fef7e29bded89fc6/raw)](https://gyazo.com/a9d9edade3e12eb4fef7e29bded89fc6)

サーバーサイドの部分は完璧でした！あともう少しです、頑張りましょう！
修正し次第、以下のChatSpace完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by yukitaka0915-se** [comment]
修正しました。

**Comment by kohei-isoda** [comment]
再提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

**Comment by yukitaka0915-se** [comment]
ありがとうございます。
